services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - "DEBUG=0"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "SECRET_KEY=vtfoac5wwipstskyj-xxe@q(-%-qm2m^4=g68$$0&6c3wcip+_n"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
